### ISSUE TITLE
欲しいAPI一覧

### ISSUE THREAD

**Issue by miso-devel** [cryptobranchoidea/kotrot#8]
# 欲しいAPI一覧
## User
- [ ] User作成
- [ ] User取得
- [ ] ログイン
- [ ] ログアウト

## Pin
- [ ] Pin取得
- [ ] Pin作成
- [ ] Pin削除

**Comment by seipan** [comment]
@hikari-8 
やりたいこととかあったりしますか？

**Comment by miso-devel** [comment]
欲しいAPIはscrapboxに移行
